use_frameworks!

target 'ModernUpperNotificationView_Example' do
  pod 'ModernUpperNotificationView', :path => '../'
  pod 'Reveal-iOS-SDK'

  target 'ModernUpperNotificationView_Tests' do
    inherit! :search_paths


  end
end
